#!/usr/local/bin/node

//require(__dirname+'/Config/TESTS/user.js') 

var request = require('request') 


var host='http://localhost:8787'




request(host+'/index.html',function(err,response,body){
  console.log(body)
})





// vim: set ft=javascript:
