#!/bin/bash  

######################################
# runs every time @ start and restart#
# panic here                         #
######################################



exec node app.js &>> log.txt

